version: "3.7"

services:
  redis:
    image: redis
    expose:
      - 6379

  worker:
      build:
        context: .
        dockerfile: DockerfileCelery
      command: [ 'celery', '-A', 'app.app', 'worker', '-l', 'info' ]
      environment:
        - BROKER_URL=redis://redis:6379
        - RESULT_BACKEND=redis://redis:6379
      depends_on:
        - redis

  flower:
      image: mher/flower:0.9.7
      command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
      ports:
        - 5557:5555
      depends_on:
        - redis
  fastapi:
    build:
      context: .
      dockerfile: DockerfileWebApi
    environment:
      REDISSERVER: redis://redis:6379
      C_FORCE_ROOT: "true"
    ports:
      - "8080:80"
    depends_on:
      - redis
